spring:
  profiles:
    active: dev
  application:
    name: tacocloud
  data:
    mongodb:
      url: mongodb://localhost:27017/tacocloud
      database: tacocloud
      port: 27017
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
logging:
  level:
    root: DEBUG
security:
    oauth2:
      client:
        registration:
          google:
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            scope: email, public_profile  