spring:
  profiles:
    active: dev
  application:
    name: tacocloud
  data:
    mongodb:
      url: mongodb://localhost:27017/tacocloud
      database: tacocloud
      port: 27017
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: INFO
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG
        org.mongodb.driver: DEBUG
#    file:
#      path: /home/marat/Dev/
#      file: TacoCloud.log
#security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: <facebook client id>
#            clientSecret: <facebook client secret>
#            scope: email, public_profile
taco:
    orders:
        pageSize: 10
#server:
#  port: 8443
#  ssl:
#    key-store: file:///home/marat/Dev/ssl/mykeys.jks
#    key-store-password: password
#    key-password: password